### ISSUE TITLE
Pathway data updates

### ISSUE THREAD

**Issue by colleenXu** [biothings/mygene.info#104]
According to @kevinxin90, the gene-pathway information is from http://consensuspathdb.org/ . However, this hasn't updated in ~2 years.

Maybe we can get the pathway data from somewhere else. For example, we can get reactome data fairly easily from https://reactome.org/download-data (including gene-pathway data).

**Comment by newgene** [comment]
@colleenXu Reactome data from mygene.info is up to date from Reactome directly. See "reactome" entry from:

http://mygene.info/v3/metadata

Other pathway data are indeed coming from CPDB

**Comment by colleenXu** [comment]
@kevinxin90 looks like the pathway info from reactome should be annotated as being from Reactome, not CPDB...

**Comment by colleenXu** [comment]
Good to know. The other resources have perhaps also updated within the past 2 years?

**Comment by newgene** [comment]
CPDB Pathway data in MyGene.info is already the latest version `Release 35 (05.06.2021)` (see "src.cpdb" from http://mygene.info/v3/metadata).

**Comment by colleenXu** [comment]
Great! I can see on the website that this was the first release in a while. 

http://cpdb.molgen.mpg.de/CPDB

19.06.2021    ConsensusPathDB version 35 has been released. In addition to an updated content, this release features new functionality: enrichment and over-representation analysis of functional gene sets defined by transcription factor and miRNA regulatory interactions.
15.01.2019    ConsensusPathDB version 34 has been released.
