### ISSUE TITLE
No hits for gene symbols with parentheses

### ISSUE THREAD

**Issue by eweitz** [biothings/mygene.info#112]
Firstly, thank you for MyGene.info!  I use it to show [related genes with Ideogram.js](https://eweitz.github.io/ideogram/related-genes?q=RELN), and find it phenomenally useful.

When I look up a gene that has a symbol containing parentheses, I get no hits from MyGene.info, but I do from other APIs.  

Examples:

### Su(H)
* MyGene.info: https://mygene.info/v3/query?q=symbol:Su(H)&species=7227
* Ensembl: https://rest.ensembl.org/lookup/symbol/drosophila_melanogaster/Su(H)?content-type=application/json

### Gt(ROSA)26Sor
* MyGene.info: https://mygene.info/v3/query?q=symbol:Gt(ROSA)26Sor&species=10090
* Ensembl: https://rest.ensembl.org/lookup/symbol/mus_musculus/Gt(ROSA)26Sor?content-type=application/json

Queries work for genes that have no parenthesis, e.g. https://mygene.info/v3/query?q=symbol:Reln&species=10090.  I can work around this by using other APIs, but I'd prefer to use MyGene.info as its speed and interface are really delightful.

Any idea what might cause this seeming bug, and how feasible a fix is?

**Comment by newgene** [comment]
@eweitz MyGene.info supports more complexed queries where `(` and `)` are reserved for [grouping queries](https://docs.mygene.info/en/latest/doc/query_service.html#boolean-operators-and-grouping), so if your query term contains them, you do need to escape them with `\`, then your queries should work as expected with MyGene.info:

https://mygene.info/v3/query?q=symbol:Su\(H\)&species=7227

https://mygene.info/v3/query?q=symbol:Gt\(ROSA\)26Sor&species=10090

Your [Ideogram.js](https://eweitz.github.io/ideogram/) looks very cool. Glad that MyGene.info contributes to your project to make it work.

**Comment by eweitz** [comment]
That solved my problem -- thanks, Chunlei!
