### ISSUE TITLE
Consistently order data in lists

### ISSUE THREAD

**Issue by stuppie** [biothings/mygene.info#12]
There are many (Entrez) genes which match multiple genes in Ensembl. The data for each ensembl field is a list and the order of the values in each field is not guaranteed to be the same. This makes it impossible to determine which values belong to which gene. 

For example: [this gene](https://mygene.info/v3/gene/856015).
There are two ensembl genes linked: YBR181C and YPL090C (in that order).
The genomic positions (chromosomes) are (in order): XVI and II.
However: YBR181C is on chromosome II, and YPL090C is on chromosome XVI.
The order is not correct, and is not guaranteed to be consistent. This makes it impossible to match the ensembl ID with the correct gene's genomic position.

**Comment by stuppie** [comment]
Just another use case for this, there are many genes like [this](https://mygene.info/v3/gene/1565?fields=genomic_pos,ensembl,entrezgene,genomic_pos_hg19,refseq,uniprot) where there are many genomic positions and ensembl entries, however only one of them is the "main" ensembl identifier ([ENSG00000100197](http://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000100197;r=22:42126499-42130906;t=ENST00000360608)). It is the main identifier because it is the only located on a chromosome, whereas the other are on haplotype chromosomes, also this is the ID that is used by other databases to xref to ensembl (example [uniprot](http://www.uniprot.org/uniprot/P10635#expression)). But we can't determine which ensembl ID to use from the mygene response. It would be great to fix this!

**Comment by sirloon** [comment]
fixed as of 65abcb658802b1685c3f3ba44e565874099029f6
added "ensemblgene" under genomic_pos so genomic positions can be mapped/associated to data under "ensembl" key
