### ISSUE TITLE
Transcript-specific matching with mygene.info?

### ISSUE THREAD

**Issue by sigven** [biothings/mygene.info#123]
Hi,

I have tried your service in various ways, most frequently with the [R client](https://github.com/biothings/mygene.R), and was curious if I could use the service to get transcript-specific annotations, which I have not yet succeded in doing. 

Example: Let's say I am interested in a particular isoform of [MITF](https://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000187098;r=3:69739456-69968336). I want to get the corresponding RefSeq mRNA and UniProt accession for [ENST00000352241.9](https://www.ensembl.org/Homo_sapiens/Transcript/Summary?db=core;g=ENSG00000187098;r=3:69739456-69968336;t=ENST00000352241). I seem to get the full set of transcript cross-references (RefSeq, UniProt) whatever transcript i use as a query, and this might be the intended function. But is there any way one can get transcript-specific annotations using mygene.info?

kind regards,
Sigve

**Comment by erikyao** [comment]
Hi @sigven, thanks for reaching out!

I think it's possible to get transcript-specific ExAC annotations, as with https://mygene.info/v3/query?q=symbol:MITF%20AND%20exac.transcript:ENST00000352241&fields=exac

Note that the query string is actually `q=symbol:MITF AND exac.transcript:ENST00000352241` with the white spaces encoded. You can change the tailing `fields=exac` to `fields=all` to explore, but I don't think we can manage to filter other sources of annotations by transcripts.

On the other hand, queries on ensembl transcripts, as with https://mygene.info/v3/query?q=symbol:MITF%20AND%20ensembl.transcript:ENST00000352241&fields=ensembl, are not transcript-specific, but you can filter out the information you need if possible.

**Comment by sigven** [comment]
Thanks for the feedback, @erikyao! Will look into the ExAC annotations to see what can be pulled out there.

regards,
Sigve
