### ISSUE TITLE
query API returns empty summary on some genes

### ISSUE THREAD

**Issue by jingjingbic** [biothings/mygene.info#129]
We are using this function ( https://mygene.info/v3/query?q=symbol:POLA2&size=1&species=human&fields=name,summary
) to get the summary of gene POLA2, the call returns no summary. However, if we search this gene in NCBI, we can see there is a summary for this gene on this page https://www.ncbi.nlm.nih.gov/gene/23649. Does Mygene.info pull the summary value from NCBI or from another data source? Query on DRG1 has the similar issue.

**Comment by newgene** [comment]
We contacted NCBI helpdesk and confirmed this:

>We currently do not add the summaries imported from the Alliance of Genome Resources onto the RefSeq transcript records. Summaries are also not added to model RefSeqs.

Instead of Refseq records, the complete set of gene summary text are available from NCBI's ASN1 binary dump files. We can modify our pipeline to extract gene summary from these files instead. A separate issue #130 was created for this task.

**Comment by jal347** [comment]
Temporary fix to human genes is done.
