### ISSUE TITLE
All uniprot.Swiss-Prot are missing

### ISSUE THREAD

**Issue by leexgh** [biothings/mygene.info#140]
All uniprot.Swiss-Prot are missing in the response. For example from your documentation:
https://docs.mygene.info/en/v3/doc/annotation_service.html, go to https://mygene.info/v3/gene/1017?fields=uniprot, it should have `"Swiss-Prot": "P24941"` like the screenshot below from the documentation.
<img width="217" alt="image" src="https://github.com/biothings/mygene.info/assets/16869603/3be3e942-f367-48ed-8b4c-a1c448c1fdfd">
But now in the response the `"Swiss-Prot"` field is missing:
<img width="674" alt="image" src="https://github.com/biothings/mygene.info/assets/16869603/f72a5183-5f40-4b13-8980-1a3b8ad09694">

Same problem happens to all other genes like https://mygene.info/v3/gene/367?fields=uniprot and https://mygene.info/v3/gene/120?fields=uniprot

**Comment by newgene** [comment]
@leexgh We saw this issue yesterday too from a recent Uniprot update, a fix will be out today (if the process goes smoothly). Will update here when it's live.

**Comment by jal347** [comment]
@leexgh We have the fix out now! Let me know if you have any other issues.

**Comment by leexgh** [comment]
@jal347 @newgene Thank you!

**Comment by leexgh** [comment]
@newgene @jal347 Thanks for fixing this, but gene AR (entrez ID 367) doesn't have uniprot information anymore, do you know the reason? https://mygene.info/v3/gene/367?fields=uniprot
