### ISSUE TITLE
Incorrect gene aliases returned

### ISSUE THREAD

**Issue by amayzhang-fluent** [biothings/mygene.info#146]
Hi, I was trying to test out your tool to obtain gene aliases for human and mouse genes. 

However, when comparing to my usual go-to (biomaRt), I noticed quite a few incorrect aliases. 

I've included a screenshot illustrating a simple example where aliases are incorrectly shared across distinct genes: 
![image](https://github.com/biothings/mygene.info/assets/159966917/dec9bd16-bd68-43e6-87bf-92564c8b4680)

Thanks

**Comment by jal347** [comment]
Hi, for our data ingestion we use the NCBI website to source our gene alias fields. If you go to the links below, you can see that our api is consistent with the **Also Known As** fields.

https://www.ncbi.nlm.nih.gov/gene/?term=ENSG00000120837
https://www.ncbi.nlm.nih.gov/gene/?term=ENSG00000001167

If this is an error on the NCBI-side, we update our mygene.info api on a weekly basis so we will have the updated value once they make their updates.
