### ISSUE TITLE
UMLS CUIs for genes

### ISSUE THREAD

**Issue by mmayers12** [biothings/mygene.info#18]
Is there any way they can be added?  Right now, getting some kind of a map from EntrezGeneID to UMLS CUI (or vice versa) is an incredibly convoluted process.

[Here is an example of the gene FOXP3](https://ncim.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&code=C1416467). I can get the CUI for a single gene from here, but I have a list of thousands of genes for which I need to translate IDs, making this inefficient.

It looks like data for UMLS CUIs could be [available for download here](https://www.nlm.nih.gov/research/umls/licensedcontent/umlsknowledgesources.html).

**Comment by veleritas** [comment]
UMLS CUIs have now been added to production. This issue can be closed.

**Comment by andrewsu** [comment]
Completed by @veleritas in https://github.com/biothings/mygene.info/commit/15cc71dd8fcf6978514f9b340cb808c569a1e861
