### ISSUE TITLE
add ortholog data from panther

### ISSUE THREAD

**Issue by andrewsu** [biothings/mygene.info#23]
data files at ftp://ftp.pantherdb.org/ortholog/current_release

Need to contact Paul Thomas about permission to redistribute (TOU: http://pantherdb.org/tou.jsp)

**Comment by sirloon** [comment]
deployed to prod as of build 20180805
Source as a plugin written by @AnnaTSW0609 https://github.com/biothings/mygene.info/tree/master/src/plugins/PantherDB
