### ISSUE TITLE
Species field parsing

### ISSUE THREAD

**Issue by stuppie** [biothings/mygene.info#29]
There's something weird going on with the species field I think. Looks like its only considering the first 10 values.

https://mygene.info/v3/query?q=__all__&species=9606 gives 96245 hits

The same query plus 9 more taxids gives 150569 hits
https://mygene.info/v3/query?q=__all__&species=9606,3702,107806,272634,260799,198094,265311,272947,471472,331636

But add another, say, [10090](https://mygene.info/v3/query?q=__all__&species=10090), which we know has genes, and you still get 150569 hits
https://mygene.info/v3/query?q=__all__&species=9606,3702,107806,272634,260799,198094,265311,272947,471472,331636,10090

**Comment by cyrus0824** [comment]
The number of species in 1 request was previously capped at 10, this is now increased to 1000.  Your final query now gives 252535 hits.
