### ISSUE TITLE
Import genomes of Myxococcus Xanthus

### ISSUE THREAD

**Issue by djow2019** [biothings/mygene.info#45]
I'm working on creating a "MyxoBase" for the myxo research community. Since wikigenomes uses WikiData as its main database, I need to import the annotated genes of 3 different strains into WD. But to do that, I need the genes in MyGene.Info to run the MicrobeBot. 

The 3 strains of myxo are as follows (taxid):
246197, 1198133, 1198538 (The first three strains).
The taxon tree is listed here: https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=34.

**Comment by newgene** [comment]
Incoming NCBI data sources do not contain genes from these species yet. When they are available, the gene annotations will be imported into MyGene.info automatically.
