### ISSUE TITLE
Couldn't query on hgnc using POST method

### ISSUE THREAD

**Issue by kevinxin90** [biothings/mygene.info#46]
Trying to query based on hgnc id:

This returns results: http://mygene.info/v3/query?q=hgnc:1771

However this doesn't: 
`import requests`
` requests.post('http://mygene.info/v3/query', params='q=1771&scopes=hgnc').json()`

**Comment by cyrus0824** [comment]
@kevinxin90 this issue should be fixed by a recent commit.  Can you verify that it's working for you?  This is my output:
``` python
In [1]: import requests

In [2]: requests.post('http://mygene.info/v3/query', params='q=1771&scopes=hgnc').json()
Out[2]:
[{'_id': '1017',
  '_score': 11.891228,
  'entrezgene': 1017,
  'name': 'cyclin dependent kinase 2',
  'query': '1771',
  'symbol': 'CDK2',
  'taxid': 9606}]
```

**Comment by kevinxin90** [comment]
@cyrus0824 It works! Great!
