### ISSUE TITLE
How are the Entrez and Ensembl mappings determined?

### ISSUE THREAD

**Issue by stuppie** [biothings/mygene.info#47]
I'm confused on how entrez and ensembl are merged. There are lots of genes with entrez and ensembl mapping that I can't find online. For example:

https://mygene.info/v3/gene/2576  (GAGE4)
has 
"entrezgene": "2576" (https://www.ncbi.nlm.nih.gov/gene?cmd=retrieve&dopt=default&list_uids=2576)
and
"ensembl" "gene": "ENSG00000215269", (https://uswest.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000215269;r=X:49570434-49577754;t=ENST00000445148)
"ensembl" "gene": "ENSG00000236362" (http://uswest.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000236362;r=X:49551278-49568218)

On the entrez page, I see a entrez link out to: ENSG00000215269 but not to ENSG00000236362.
So how/why was ENSG00000236362 mapped to 2576?

Please let me know, Thanks!

**Comment by stuppie** [comment]
See also: https://github.com/biothings/mygene.info/issues/39

**Comment by newgene** [comment]
Close this one now. See more discussions on related #39
