### ISSUE TITLE
I can't retrieve KEGG info from zebrafish geneIDs

### ISSUE THREAD

**Issue by mlosilla** [biothings/mygene.info#53]
Hi,
I am using the queryMany function from the mygene R package 1.14.0 to retrieve annotations for zebrafish. 

I have tried "refseq" and "entrezgene" as scopes, and it works great for several fields I have tried, except for those related to KEGG pathways ("pathway.kegg", "kegg", "pathway.kegg.name", "pathway.kegg.id").

code example:

 Drerio.gene.ids <- queryMany(prot, scopes = "refseq", fields=c("entrezgene", "symbol", "name", "go", "pathway.kegg"), species=7955,  returnall=TRUE)

As troubleshooting, I retrieved the KEGG fields but with a human entrezgene list as the scope, and it worked just fine.

Is there something I am missing?

Thanks

**Comment by newgene** [comment]
@mlosilla it has been a while since you posted this here. Hope the issue has been solved by now. But if not, please ping us again here.
