### ISSUE TITLE
ENSG00000268000 not found

### ISSUE THREAD

**Issue by andrewsu** [biothings/mygene.info#60]
These two calls return nothing:
http://mygene.info/v3/query?q=ENSG00000268000 
http://mygene.info/v3/gene/ENSG00000268000

Gene exists in ensembl:
http://grch37.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000268000

not sure if it's a true data issue, but logging it to investigate further...

**Comment by sirloon** [comment]
@andrewsu one possible explanation could be latest ensembl release is 95 according the link to their website, but we currently run 94. Not sure how to test this gene on release 94

**Comment by andrewsu** [comment]
good point.  This gene history link http://grch37.ensembl.org/Homo_sapiens/Gene/Idhistory?g=ENSG00000268000;r=19:50003781-50004614;t=ENST00000602157 shows that it is currently on ENSG00000268000.1 (version 1), so perhaps it was only introduced in 95...

**Comment by andrewsu** [comment]
Looks like this explanation is correct.  http://oct2018.archive.ensembl.org/Homo_sapiens/Gene/Idhistory?g=ENSG00000268000 (searching version 94) report "This identifier is not in the current EnsEMBL database."  Thanks @sirloon!

**Comment by andrewsu** [comment]
... and just to note that links to archived ensembl versions is here: https://uswest.ensembl.org/info/website/archives/index.html
