### ISSUE TITLE
demonstrate use of 'fields' parameter for python client

### ISSUE THREAD

**Issue by andrewsu** [biothings/mygene.info#63]
In the documentation at https://pypi.org/project/mygene/, we should add some documentation of the `fields` parameter.  e.g.:

```
mg.querymany([1017, '695', 'NA_TEST'], scopes='entrezgene', species='human',fields='entrezgene,ensembl,uniprot')
```

**Comment by newgene** [comment]
updated in https://github.com/biothings/mygene.py/commit/069b83a2c5a49adce778eaefbf69089549b2afd3

Actually pypi page will be updated upon the next release.
