### ISSUE TITLE
Fetch all feature for POST query

### ISSUE THREAD

**Issue by kevinxin90** [biothings/mygene.info#65]
fetch_all is a valid parameter for the query endpoint using the HTTP GET method. But it's not a valid parameter for the query endpoint using the HTTP POST method (making it difficult to get all results back in batch query mode).

**Comment by namespacestd0** [comment]
Batch pagination is introduced in https://github.com/biothings/biothings.api/commit/eb9bd40ad4c0c02f21622b55fbf02a7ed3f2bbea. Please use this instead.
