### ISSUE TITLE
Data source: load ClinGen gene-disease validity data

### ISSUE THREAD

**Issue by andrewsu** [biothings/mygene.info#69]
more info: https://github.com/SuLab/GeneWikiCentral/issues/116

**Comment by newgene** [comment]
Integrated to MyGene.info API now:

http://mygene.info/v3/query?q=_exists_:clingen&fields=clingen,name,symbol

An example data object:

```
{
    "_id": "23676",
    "_score": 1.55,
    "clingen": {
        "_license": "https://www.clinicalgenome.org/docs/terms-of-use/",
        "clinical_validity": {
            "classification": "definitive",
            "disease_label": "nonsyndromic genetic deafness",
            "mondo": "MONDO:0019497",
            "online_report": "https://search.clinicalgenome.org/kb/gene-validity/29773bee-1f13-43f6-bda0-c5a646efccd7--2017-09-12T16:00:00",
            "sop": "SOP6"
        }
    },
    "name": "small muscle protein X-linked",
    "symbol": "SMPX"
}
```


MyGene.info data source: 

[src/hub/dataload/sources/clingen](https://github.com/biothings/mygene.info/tree/master/src/hub/dataload/sources/clingen)

Based on the code from @chvbs2000: 

https://github.com/chvbs2000/ClinGen
