### ISSUE TITLE
update genome_assembly returned from metadata

### ISSUE THREAD

**Issue by newgene** [biothings/mygene.info#74]
"genome_assembly" field from [/metadata](http://mygene.info/metadata) should be updated based on this commit from BioGPS:

https://github.com/SuLab/biogps_core/commit/ab66142808139ea76d55989d482c53e1b8a0ea85

**Comment by sirloon** [comment]
@newgene can you specify more ? currently we have: 

![image](https://user-images.githubusercontent.com/2883770/67057086-f048a780-f103-11e9-8c77-ecfa927910eb.png)

**Comment by newgene** [comment]
@sirloon You just need to check the "name" and "assembly" fields from the above biogps commit. I can see only one new key "thale-cress" needs to be added, other keys just need to update their values.
