### ISSUE TITLE
Provide export of MyGene.info

### ISSUE THREAD

**Issue by hammer** [biothings/mygene.info#78]
I'd love to work with the MyGene.info data as a bulk export rather than via an API.

There are many ways I could imagine this data being made available:
- [Elasticsearch snapshot](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html)
- JSON, perhaps exported via https://github.com/taskrabbit/elasticsearch-dump.
- Parquet, perhaps converted from JSON via Spark.

Would the BioThings team ever consider making their data available for download? I'd be happy to pay for the bandwidth consumed via a requester pays setup (e.g. [Amazon](https://docs.aws.amazon.com/AmazonS3/latest/dev/RequesterPaysBuckets.html), [Google](https://cloud.google.com/storage/docs/requester-pays)).

**Comment by newgene** [comment]
Hi @hammer, thanks for reaching out. 

* The short answer:
  - We currently don't have the ready dump file available for MyGene.info, but we are happy to produce one for you and share it with you individually.
  - Alternatively, we have already done a bit further to allow users to run MyGene.info locally (or within the intranet) if that is your ultimate purpose. Effectively, you will have access to the Elasticsearch snapshots via your local server. More details here: http://docs.biothings.io/en/latest/doc/standalone.html

* Let me explain a bit more on these:
   MyGene.info updates weekly. To achieve this quick turn-around, our pipeline does not produce the entire Elasticsearch (ES) index every week. Most of the time, it just produces incremental updates and applies them to our production ES cluster. That way, the whole process can be done within ten minutes. Only when there are big data updates, we will rebuild a new ES index and update our production via snapshots.

   If you set up your standalone MyGene.info server as documented, you will have access to these incremental data files and the "full" ES snapshot when there is a "full" release. Your local MyGene.info server will be able to keep in-sync with our production server. @sirloon from our team is the main brain behind this, he can help you to set up and explain more on this if you want to go that route.

   If you want to just get a quick dump, we can export one for you. But if you want to make the process automated for future releases, extra works are needed on our end.

**Comment by newgene** [comment]
closing this issue for now.
