### ISSUE TITLE
add UMLS entries for proteins

### ISSUE THREAD

**Issue by andrewsu** [biothings/mygene.info#79]
We currently have mappings to UMLS CUIs for genes (see #18).  For example, on the entry for NOS3 http://mygene.info/v3/gene/4846, we have:

```
"umls": {
    "cui": "C1328053"
},
```

But since mygene effectively merges gene and protein objects, we should probably also add mappings to UMLS CUIs for proteins.  For NOS3, that identifier would be https://uts.nlm.nih.gov/metathesaurus.html?cui=C0669365, which looks like it can be joined to our gene entries via Swiss-Prot identifiers in MRSAT.RRF (which I believe is a mapping file provided by UMLS)

![image](https://user-images.githubusercontent.com/2635409/75374443-28fe4780-5881-11ea-96cc-b4714bdd540f.png)

(RefSeq also appears to be a common identifier that could be used for mapping...)

If that's all correct, then I'd suggest adding those mappings, perhaps in a structure like this:

```
"umls": {
    "cui": "C1328053",
    "protein_cui": "C0669365"
},
```

**Comment by kevinxin90** [comment]
Updated in: 8dfc9240858ca5a5a196add8da6efd323051c88c. Also deployed to the production.

Example query: http://mygene.info/v3/gene/1017?fields=umls
