### ISSUE TITLE
Update UMLS data source

### ISSUE THREAD

**Issue by newgene** [biothings/mygene.info#80]
[This data source](https://github.com/biothings/mygene.info/tree/master/src/hub/dataload/sources/umls) is manually updated, 2019AB version is now available:

https://www.nlm.nih.gov/research/umls/licensedcontent/umlsknowledgesources.html

While we update UMLS, we can tackle this related issue #79 as well.

**Comment by kevinxin90** [comment]
Updated in: 8dfc9240858ca5a5a196add8da6efd323051c88c. Also deployed to the production.

Example query: http://mygene.info/v3/gene/1017?fields=umls
