### ISSUE TITLE
Retrieve full table given two fields

### ISSUE THREAD

**Issue by ilibarra** [biothings/mygene.info#82]
Dear MyGene team,

I have a user question: Is it possible to retrieve one complete mapping table between any two identifiers without having to submit gene names each time? E.g. get the full ensembl gene IDs for all symbols in mouse, or all symbols/ensembl ID pairs in human.

Something like `mg.querymany`, but without names as input. Maybe `mg.queryall`.
```
mg = mygene.MyGeneInfo()
out = mg.queryall(scopes='symbol', fields='ensembl.gene', species='mouse', as_dataframe=True, returnall=True)
```

Thank you for your consideration,
Ignacio

**Comment by kevinxin90** [comment]
You can do:

```
mg = mygene.MyGeneInfo()
gene_client.query('taxid:10090', fields='symbol, ensembl.gene',fetch_all=True)
```
This will fetch you symbols and ensemble gene ids for all mouse genes as a Python Generator.

You can then manipulate the generator as you wish.

**Comment by ilibarra** [comment]
Thank you for the prompt reply!
