### ISSUE TITLE
genomic position query in batch mode.

### ISSUE THREAD

**Issue by brentp** [biothings/mygene.info#87]
Hi, I can use e.g. `v3/query?q=chr2:22000000-24000000` but this does not work with a post request to a batch query.
I have set `scopes=symbol,entrezgene,ensemblgene,retired` as I didn't see one that includes genomic position. Is there a way I can do a batch (post) query where some of the `q` entries are genomic coordinates?
thanks, and thanks for the great mygene.info service.

**Comment by kevinxin90** [comment]
Hi @brentp, after discussing with the team, we decide not to enable batch queries for the genome range type of query. These range queries put lots of pressure on our server, and we're afraid that enabling batch queries for them without limit would be too much pressure for the server. So we would still recommend you to make multiple genomic range queries synchronously. Thanks!

**Comment by brentp** [comment]
i understand. thanks for the reply.
