### ISSUE TITLE
table of fields not rendering correctly in documentation

### ISSUE THREAD

**Issue by andrewsu** [biothings/mygene.info#88]
At this link, https://docs.mygene.info/en/latest/doc/data.html#available-fields used to show a nice table that showed all available fields in dot notation.  That for some reason is not rendering correctly.  

![image](https://user-images.githubusercontent.com/2635409/88210662-62a56580-cc09-11ea-8732-1c128b1a9bd5.png)

That also seems to affect all the docs for all the biothings API instances: https://docs.myvariant.info/en/latest/doc/data.html#available-fields https://docs.mychem.info/en/latest/doc/data.html#available-fields

**Comment by newgene** [comment]
fixed in fc75bc85ff29c8d1c63c2d060912c4ab19572fa3 and 6ccb74773271b78ebae3fdb4e7ae261ab2850a85. Cross-origin JSONP ajax call was blocked by the browser now, switching to the regular ajax call fixed the issue.
