### ISSUE TITLE
Capture HomoloGene version number

### ISSUE THREAD

**Issue by stuppie** [biothings/mygene.info#9]
HomoloGene data is downloaded from Entrez, but it has its own versioning system separate from Entrez. The version number is in this file in the same dir (ftp://ftp.ncbi.nih.gov/pub/HomoloGene/current/). Is it possible to add this to the [metadata](https://mygene.info/v3/metadata) page?

**Comment by newgene** [comment]
Good idea. We will add the HomoloGene version in our [metadata](https://mygene.info/v3/metadata) endpoint.

**Comment by newgene** [comment]
"homologene" version is now reported in the [metadata ](https://mygene.info/v3/metadata) endpoint, under "src.homologene.version".
