### ISSUE TITLE
missing ortholog data

### ISSUE THREAD

**Issue by ftwkoopmans** [biothings/mygene.info#95]
I would like to use the mygene.info api to find human orthologs for a set of entrez gene IDs. However, I noticed that some genes  which have ortholog mappings on pantherdb do not show crossreferences through the mygene.info api.

Here's a case study; 
The mygene.info record for the _mouse_ gene "Neurexin 3" does not show a human ortholog, but pantherdb.org does have this data (links shown below). In reverse, the mygene.info record for the _human_ gene "Neurexin 3" does show a mouse ortholog.

1) why are known pantherdb LDO orthologs missing from the mygene.info record ?
2) can we use the mygene.info api to filter for the target species of interest in ortholog records (would be much more efficient for most use-cases) ? For instance, return only pantherdb and homologene mappings to taxid=9606
3) could the mygene.info _id be included with each pantherdb ortholog (so we don't have to fire a follow-up query to find the actual gene ID for each ortholog) ?
4) there is no homologene data in the mygene.info record for Nrxn3 in human (link below, entrez ID: 9369). However, when I go to the ncbi site https://www.ncbi.nlm.nih.gov/gene/9369#homology and click on the provided link, it seems that the ncbi database contains expected orthologs; https://www.ncbi.nlm.nih.gov/gene/?Term=ortholog_gene_9369[group]

mygene.info data for gene; Nrxn3
Mouse: https://mygene.info/v3/gene/18191?fields=taxid,name,symbol,pantherdb,homologene
Human: https://mygene.info/v3/gene/9369?fields=taxid,name,symbol,pantherdb,homologene

pantherdb data for gene; Nrxn3
Mouse: http://pantherdb.org/genes/gene.do?acc=MOUSE%7CMGI%3DMGI%3D1096389%7CUniProtKB%3DQ6P9K9
Human: http://pantherdb.org/genes/gene.do?acc=HUMAN%7CHGNC%3D8010%7CUniProtKB%3DQ9Y4C0

**Comment by jal347** [comment]
I fixed the issue of the missing pantherdb othologs. I am still looking into the homologene issue.

**Comment by jal347** [comment]
The homologene data has been retired from ncbi:

https://ftp.ncbi.nih.gov/pub/HomoloGene/README

"The last HomoloGene build (build 68) was produced in 2014, and is no longer aligned with
current data in NCBI RefSeq and Gene"
